[profile.default]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true
extra_output = ["metadata", "storageLayout", "evm.deployedBytecode.immutableReferences"]

test = "forge-test"
broadcast = "broadcast-test"

libs = [
    "lib",
    "node_modules",
]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/",
    "wormhole-solidity/=modules/wormhole",
    "opensea/=modules/opensea",
    "ERC5058/=modules/ERC5058",
    "ERC5192/=modules/ERC5192",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
